type = "service_account"
project_id = "arte-paris-api"
private_key_id = "0dc1126f722264e083ceb1d2916244fb422614bc"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDjpr5OcVZgIiMC
KzpqlLVDkS1Y3YxMVkvaJjY+2V3eFkLBHaJGe67bwJAjyniEkN8zRVe7D+r+QSfp
jsf/e07oX3KKhqglYAix8eIJiIjggaU5FEMjgwWTAQI/+0KWy/MluVGsd0IkJ2wh
So+CONtv5M5t1FUF4d+db1e6oplZ/CAEYtlSsEfkGpz+osW+xVKoEa9l/uTTMCf/
2Vpkk2BD4dc3CBHher98NJRblobEkAxobcH+nMeQfRJb4iPeX8UM42/njT9YtlIY
WrIva3D73I6sVPEPl+5VDFpWMpspAOtlJQcbIUQqzLdgW34gFFQWyJgxKHeV0leY
qZ5RyunlAgMBAAECggEAEABT5xKbViWAHXJpaD1sokOtks37ww/bxAkkjfVcXjRl
W8qX8elWqJaX6xQbtYGzVpi8qmbbhySQSB/jmecSbE3tMKR3ZC0kX1GXqEDjEhi6
wtDUSUY32ZXcESA5lXzfadrlTUCSsxTcSljBzo7tiadlBR5EHaY7QAcn/PPZ4JOw
uAJ7alhb61PnJhSK7jJE3SBOkYXXVUjLGSBkPkhLr4CHTKJ59kwKpzUPjdQvtUF0
uOp67afAziwnSectfBZGPZ6MIlZpz/7id6PfuiR3mbgxJRI1AeNRUJCfjbvixRHa
oP2CCUGg4qqN/mxTMt123zWE9FgJDQeMejtXp7GpoQKBgQD9keqNXXRVO2xkjHou
iz1p15lHZ7uAWBTtBpP7iBIw15ga4om8by14vKdPkBYLOuOZNA+Ks2DxC3DPVhTn
izHb0tcVk0Kf3GAfw7aRiNHXGAxjmZe1ZpcrE/11dtp34W26crzKc5+1j3uiQ5No
KyIQh0R8tukG/uAfkB2XP5T+0QKBgQDl1T2rsXJlNq5cWPH9KmfeLYTYCgWofv1P
fB6kmLr7zmtQLLcYzOoboxYTlzGX/qWkulEqMuHk6txxXjGGR1sExPdjMxyELSIg
S6y/s58IqmOrEo2L5zo27+ySGnpe99kCKZyrUIYwiCzIsyyHQsvEF8LJCqgQI1HV
PFLneboG1QKBgQD89G2KLKp6xFbzT3grqlfPmHaeVwsjk7r8YU2K5UlQVCK23zsM
MdSo13oI0vJKraqTEO5YLW4NyJ33GCaufZt1cbWDHm6eTxfNWE5ujJDZBHKHgZdo
LTmsjbqRTcnPQaFXGFLhm8q9Mq/hRYxtpGnNF0PpLgb1JZmrovcCBTm7oQKBgEen
Q6LTn6aOda20zTzwi5Fo/5GbDkiJzs+JEsSeGS2IHUzRpAPHXvVe0vMon/2TFnFU
5RkS4/pKfo+ZnjcO6AGEptv2g11x9MG81g6uIVbCSHB9SEPlwvB9vHOQbbZN7woN
jxqZ8DwROGUZ9zf0SzLHdaLX/62IVWr1c6NW//hBAoGATxwSfse5LbGQ1cQrvIPj
dc6GqR37rxbqC0qYUPl4QLCmFowHNMDNtQl5pJ2P+vT2bLGx4OzYeFCJZUOc+XWc
tzM2mIAk/SKEya98PE4At3L+hiCEL37iDuIIVo4r7HQyOwvQArO53zQ3HHhCn68m
5rlrAiTZt2hGzCX/UDMXn4E=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@arte-paris-api.iam.gserviceaccount.com"
client_id = "100351205257047803410"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40arte-paris-api.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
