[firebase]
type = "service_account"
project_id = "arte-paris-api"
private_key_id = "0562938c8aeff1454823130eb2ee735bc89a34e8"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCJygl8CK/zzFeM
0BbWdtuh+kjWL9IkrvcrhZJjFYC01FscoGLTCuLR0Uq6QGqTnSYt96t9qOvgOpzn
HMeSvlE/ah5OV4x9SCZDcE8hXhVQll+s2rh2Sk39GTTqG7wAr80Wc/M0R8p9r0b0
2x/kUZbvJPreNi07NKUMZqVITiA5TyxKJ3FaDdFcz5/EUUm9ePTQP87st/sSFv8w
+XLd+twL7ovaeVnTo+Vgmt45Nh9afQr8wRZK+tkfs2p6NxRqKqRLQSxxtXWiavSI
ReilXc7DADdxbqvJvDI8K7324X81I9cmHq07P5ecjq846nEe7If7FQTdsHya6jGl
BLU4ftHJAgMBAAECggEAHxFwDAiFa+pCP1zYGWlZYm9lpu3Ha0AMOUL32+GIUL2l
AZJkVgOZWwfe2poVrcz8Q9cZUs8YyElPAYlqsnq5JRxPUwjIg6MWBZS4MuTc13vg
fMAgYYOljBD37mVsgZciHhLs3nflf2tbC3CxAzEmYCutaRc8IaJgKKioUeJTv7f2
mtJFGvkOgz7wvShPZTr3T5cYCryT+3c1CeLYtIR6vZG5GGsI5DJVy36X9Hs5/zpP
TxM9992t0xss4sixkInOnaR5hLNHA6YvuplouzbIfTzAt4k6rwjtB1vbS+Kve3lW
0b6tZFzdVScRSSmCZdTL+9M1NdpSMuKTQz8wdJUapQKBgQDCz4RH6h4c351NAOB1
0MLTW0QsIaJmzTc0k1NQoXQyG+0HbdcvkPtiQqCIlsa57UbDKxho6PM/k25YQ1DD
mUAkDkD8v12utZjSKe+6M/DsByq3GEzruhHPQdDbPxzTOuy1l5e2NfT/mPW3IUOE
nBRco4sbhHdg1PyPPvnRnt8VWwKBgQC1EX+zUQbyGyalpAxjxo6oIDViR+UBxlFG
EQwuM381vj4j+lxTZsIMWF7/bYqI82H/YTcU5K2Ae8bzcoUETu0Lf/l/Er0GVT9t
G+DodbIMkkTcu7UkEcBRaACC2Z6+IWN1a/3OhBU5IQZCkLMuAhHy44y8GLuuJFT0
Fduz+tIKqwKBgQCMoiA9hi5s66Tz5PElPCqZR+aD8Vf63KTAyKY5rARk9DH9zfat
OP2w5qZbVHVr3XXbCO5bNef8emMLRrU0LxrVrJCPpVps+F21Ql70TfDbgyT7/ofx
GGco9rteu0YE2yHsyd3UxUjzh6nCpTnHrqEoa0vN9qfzeG5GvtC72fPzxwKBgQCk
jKCGry4mu3Hlui3gRsPCGnMpO7jsYfPePwPYwMfsaVVDkPRyfsH+Qhki+8OYLcZz
NT+/Zwod516oQvyLK8bUWpq8VqUdqj8XwuwjlUIXlp2qE5PMka06zc8ZGvfeRa2D
On7PPM2ku1RbDfEn8I2rNAvjrH5zBWWG5I5jA5/6PQKBgDcWwa9FSZU6NXnU4ra+
GWaPXlNd3TcPJfzpethEpPAJvlWuwBGTEHzLA9wcnlIzZnqh4qlJqTplx3OHJcDv
+KJ4s3bl6o6ZqPHunhOmzQUN2jUcq7qaQa+P9Tl8U4EU2BEhr6y6z6M/w2bh+WoD
6cV5fyEoEgYDHeUtNA+GnfIf
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@arte-paris-api.iam.gserviceaccount.com"
client_id = "100351205257047803410"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40arte-paris-api.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

